export const MOCK_PRODUCTS = [
  {
    id: 1,
    title: 'Ручка гелевая Parker',
    price: 1500,
    category: 'Письмо',
    image: 'https://via.placeholder.com/200x200?text=Parker+Pen',
    color: 'blue',
    type: 'pen',
  },
  {
    id: 2,
    title: 'Тетрадь А5 в клетку',
    price: 85,
    category: 'Бумага',
    image: 'https://via.placeholder.com/200x200?text=Notebook',
    color: 'green',
    type: 'notebook',
  },
  {
    id: 3,
    title: 'Набор маркеров Touch',
    price: 2400,
    category: 'Творчество',
    image: 'https://via.placeholder.com/200x200?text=Markers',
    color: 'multi',
    type: 'markers',
  },
  {
    id: 4,
    title: 'Ежедневник кожаный',
    price: 1200,
    category: 'Бумага',
    image: 'https://via.placeholder.com/200x200?text=Diary',
    color: 'black',
    type: 'notebook',
  },
  {
    id: 5,
    title: 'Карандаши цветные Faber-Castell',
    price: 500,
    category: 'Творчество',
    image: 'https://via.placeholder.com/200x200?text=Colored+Pencils',
    color: 'multi',
    type: 'pencil',
  },
  {
    id: 6,
    title: 'Ручка шариковая Bic',
    price: 60,
    category: 'Письмо',
    image: 'https://via.placeholder.com/200x200?text=Bic+Pen',
    color: 'black',
    type: 'pen',
  },
  {
    id: 7,
    title: 'Скетчбук А4',
    price: 450,
    category: 'Творчество',
    image: 'https://via.placeholder.com/200x200?text=Sketchbook',
    color: 'white',
    type: 'notebook',
  },
  {
    id: 8,
    title: 'Линейка пластиковая 30 см',
    price: 70,
    category: 'Принадлежности',
    image: 'https://via.placeholder.com/200x200?text=Ruler',
    color: 'transparent',
    type: 'ruler',
  },
  {
    id: 9,
    title: 'Корректор-ручка',
    price: 120,
    category: 'Письмо',
    image: 'https://via.placeholder.com/200x200?text=Correction+Pen',
    color: 'white',
    type: 'correction',
  },
  {
    id: 10,
    title: 'Папка на молнии A4',
    price: 300,
    category: 'Бумага',
    image: 'https://via.placeholder.com/200x200?text=Folder',
    color: 'blue',
    type: 'folder',
  },
  {
    id: 11,
    title: 'Маркер перманентный черный',
    price: 150,
    category: 'Творчество',
    image: 'https://via.placeholder.com/200x200?text=Marker',
    color: 'black',
    type: 'marker',
  },
  {
    id: 12,
    title: 'Ножницы канцелярские',
    price: 200,
    category: 'Принадлежности',
    image: 'https://via.placeholder.com/200x200?text=Scissors',
    color: 'silver',
    type: 'scissors',
  },
  {
    id: 13,
    title: 'Скрепки металлические',
    price: 50,
    category: 'Принадлежности',
    image: 'https://via.placeholder.com/200x200?text=Paper+Clips',
    color: 'silver',
    type: 'clips',
  },
  {
    id: 14,
    title: 'Фломастеры Crayola',
    price: 600,
    category: 'Творчество',
    image: 'https://via.placeholder.com/200x200?text=Felt+Pens',
    color: 'multi',
    type: 'markers',
  },
  {
    id: 15,
    title: 'Клей-карандаш Pritt',
    price: 100,
    category: 'Принадлежности',
    image: 'https://via.placeholder.com/200x200?text=Glue+Stick',
    color: 'white',
    type: 'glue',
  },
  {
    id: 16,
    title: 'Ручка перьевая Lamy',
    price: 2500,
    category: 'Письмо',
    image: 'https://via.placeholder.com/200x200?text=Lamy+Pen',
    color: 'blue',
    type: 'pen',
  },
  {
    id: 17,
    title: 'Тетрадь А4 в линейку',
    price: 90,
    category: 'Бумага',
    image: 'https://via.placeholder.com/200x200?text=Notebook+A4',
    color: 'red',
    type: 'notebook',
  },
  {
    id: 18,
    title: 'Кисти для рисования набор',
    price: 350,
    category: 'Творчество',
    image: 'https://via.placeholder.com/200x200?text=Brushes',
    color: 'wood',
    type: 'brushes',
  },
  {
    id: 19,
    title: 'Ежедневник недатированный',
    price: 800,
    category: 'Бумага',
    image: 'https://via.placeholder.com/200x200?text=Diary+Undated',
    color: 'brown',
    type: 'notebook',
  },
];
